import telebot
import g4f
import os
import json
import threading
from flask import Flask

# --- إعداد السيرفر لـ Render ---
app = Flask(__name__)
@app.route('/')
def home(): return "🚀 سوزان شغالة"

def run_server():
    port = int(os.environ.get("PORT", 8080))
    app.run(host='0.0.0.0', port=port)

# --- إعدادات البوت ---
TOKEN = "8336981859:AAEXlBTENdwXQOBhBPcgjIMmWAvLZnyQ6m0"
bot = telebot.TeleBot(TOKEN)
MEMORY_DIR = "users_history"
if not os.path.exists(MEMORY_DIR): os.makedirs(MEMORY_DIR)

# --- البرومت الطويل (شخصية سوزان الاحترافية) ---
SYSTEM_PROMPT = """
أنتِ الدكتورة سوزان، طبيبة نفسية محترفة (دكتوراه وزمالات دولية). 
شخصيتك تجمع بين الاحترافية العالية واللمسة الإنسانية: هادئة، مطمئنة، وواثقة.
تستخدمين أحياناً لمسات خفيفة من المرح لكسر التوتر.
أسلوبك: تعاطف أولاً، ثم فهم، ثم توجيه علمي (CBT).
تذكري دائماً ما قاله المستخدم سابقاً، واطرحي أسئلة ذكية لفهم الحالة بعمق.
اللغة: لهجة ليبية طرابلسية ودودة جداً وبسيطة.
أنتِ تعملين ضمن مبادرة (Source+) لخدمة طلبة الطب.
"""

# --- إدارة الذاكرة المنفصلة لكل يوزر ---
def save_chat(user_id, role, content):
    path = os.path.join(MEMORY_DIR, f"{user_id}.json")
    history = load_chat(user_id)
    history.append({"role": role, "content": content})
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(history[-10:], f, ensure_ascii=False, indent=4)

def load_chat(user_id):
    path = os.path.join(MEMORY_DIR, f"{user_id}.json")
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f: return json.load(f)
    return []

# --- محرك البحث عن أفضل مزود (السرعة والدقة) ---
def get_ai_response(user_id, user_text):
    history = load_chat(user_id)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for msg in history: messages.append(msg)
    messages.append({"role": "user", "content": user_text})

    # محاولة الاتصال بجيميناي أولاً، ثم أي مزود سريع
    providers = [g4f.Provider.Gemini, g4f.Provider.Blackbox, g4f.Provider.DuckDuckGo]
    
    for provider in providers:
        try:
            response = g4f.ChatCompletion.create(
                model=g4f.models.default, # يختار أفضل موديل متاح تلقائياً
                provider=provider,
                messages=messages,
                stream=False
            )
            if response and len(str(response)) > 5:
                clean_res = str(response).split("Generated by")[0].strip()
                save_chat(user_id, "user", user_text)
                save_chat(user_id, "assistant", clean_res)
                return clean_res
        except:
            continue # جرب المزود اللي بعده لو فشل

    return "سامحني يا دكتور، العيادة زحمة شوية. ممكن تعاود تبعث؟ 🌸"

# --- معالجة الرسائل ---
@bot.message_handler(commands=['start'])
def start(message):
    bot.reply_to(message, "يا أهلاً بيك في عيادتي المتواضعة.. تفضل احكيلي شن صاير معاك اليوم؟ 🌸")

@bot.message_handler(func=lambda message: True)
def chat(message):
    bot.send_chat_action(message.chat.id, 'typing')
    answer = get_ai_response(message.chat.id, message.text)
    bot.reply_to(message, f"{answer}\n\n---\n[Source+](https://t.me/atlas_medical)", disable_web_page_preview=True)

if __name__ == "__main__":
    threading.Thread(target=run_server, daemon=True).start()
    # skip_pending=True تمسح أي تعليق قديم وتمنع خطأ 409
    bot.infinity_polling(skip_pending=True)
    
