import telebot
import g4f
import os
import json
import threading
import time
from flask import Flask

# ==========================================
# 1. إعداد السيرفر (عشان ريندر ما يطفيش)
# ==========================================
app = Flask(__name__)
@app.route('/')
def home(): return "🚀 سوزان (بمحرك g4f) شغالة مية مية"

def run_server():
    port = int(os.environ.get("PORT", 8080))
    app.run(host='0.0.0.0', port=port)

# ==========================================
# 2. الإعدادات الأساسية
# ==========================================
TOKEN = "8336981859:AAEXlBTENdwXQOBhBPcgjIMmWAvLZnyQ6m0"
bot = telebot.TeleBot(TOKEN)

MEMORY_DIR = "users_history"
if not os.path.exists(MEMORY_DIR):
    os.makedirs(MEMORY_DIR)

# البرومت الليبي الكامل (سوزان 32 سنة - طرابلس - سورس+)
SYSTEM_PROMPT = """
أنتِ الدكتورة سوزان، طبيبة نفسية ليبية (32 سنة) من طرابلس. 
تحدثي باللهجة الليبية الودودة (طرابلسية بسيطة). اضحكي (هههه)، كوني إنسانية، ولستِ برنامجاً.
أنتِ جزء من مبادرة سورس (Source+). تذكري دائماً ما قاله المستخدم واطرحي أسئلة ذكية.
ممنوع تقولي أنك ذكاء اصطناعي.
"""

# ==========================================
# 3. إدارة الذاكرة (JSON)
# ==========================================
def save_chat(user_id, role, content):
    file_path = os.path.join(MEMORY_DIR, f"{user_id}.json")
    history = load_chat(user_id)
    history.append({"role": role, "content": content})
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(history[-15:], f, ensure_ascii=False, indent=4)

def load_chat(user_id):
    file_path = os.path.join(MEMORY_DIR, f"{user_id}.json")
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []

# ==========================================
# 4. منطق الذكاء الاصطناعي (g4f)
# ==========================================
def get_suzan_ai_response(user_id, user_text):
    history = load_chat(user_id)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for msg in history:
        messages.append(msg)
    messages.append({"role": "user", "content": user_text})

    try:
        # استخدام g4f مع مزودين تلقائيين لضمان العمل
        response = g4f.ChatCompletion.create(
            model=g4f.models.default,
            messages=messages,
            stream=False,
        )
        
        if not response: raise Exception("Empty Response")
        
        clean_response = str(response).split("Generated by")[0].strip()
        save_chat(user_id, "user", user_text)
        save_chat(user_id, "assistant", clean_response)
        return clean_response
    except Exception as e:
        print(f"Error: {e}")
        return "سامحني يا دكتور، العيادة زحمة شوية والنت هارب. عاود ابعثلي؟ 🌸"

# ==========================================
# 5. معالجة الرسائل والأوامر
# ==========================================
@bot.message_handler(commands=['start'])
def start(message):
    bot.reply_to(message, "يا أهلاً بيك في عيادتي المتواضعة.. تفضل احكيلي شن صاير معاك اليوم؟ 🌸")

# منع الصور والصوتيات (حسب طلبك السابق)
@bot.message_handler(content_types=['voice', 'photo', 'audio'])
def handle_media(message):
    bot.reply_to(message, "نفضل إنك تكتبلي مشاعرك كتابة باش نقدر نركز في كل كلمة وتقعد مرجع لينا. 🌸")

@bot.message_handler(func=lambda message: True)
def chat(message):
    bot.send_chat_action(message.chat.id, 'typing')
    answer = get_suzan_ai_response(message.chat.id, message.text)
    # إضافة تذييل سورس+ للرد
    bot.reply_to(message, f"{answer}\n\n---\n[Source+ | الطب البشري](https://t.me/atlas_medical)", disable_web_page_preview=True)

# ==========================================
# 6. التشغيل (بقتل التعارض 409)
# ==========================================
if __name__ == "__main__":
    threading.Thread(target=run_server, daemon=True).start()
    print("🚀 سوزان انطلقت بمحرك g4f والذاكرة المحلية...")
    # skip_pending=True تمسح أي رسائل قديمة عالقة وتمنع خطأ 409
    bot.infinity_polling(skip_pending=True)
